### ISSUE TITLE
Switches stuck in favourites

### ISSUE THREAD

**Issue by Caban-ru** [Martvvliet/homebridge-denon-heos#11]
Switches constantly appears in main screen (favourites & Status) after restarting Homebridge

**Comment by Caban-ru** [comment]
sorry,
problem disappeared after reinstalling plugin to a new/clean HB instance

**Comment by Caban-ru** [comment]
no, problem still there(

**Comment by Martvvliet** [comment]
Yeah, that looks to be a Homekit bug as I have that too with other devices. What helps is turning the favourites switch on en off many times and than it will stay stuck on how you want it.

**Comment by Caban-ru** [comment]
tried, but no result. 
Anyway, i can use it without switches. Very good plugin, thanks!!

**Comment by Martvvliet** [comment]
Sorry, I misinterpreted your first post. This is still a bug which has the same cause as issue #10 I will transfer this issue to that post.
