### ISSUE TITLE
No Denon receiver with IP: 192.168.188.11 found in network. Using manual port: 80.

### ISSUE THREAD

**Issue by rbswift** [Martvvliet/homebridge-denon-heos#15]
Hi,

I'm getting this error when I try to run the plugin:

> Jan 31 15:24:26 pi4 homebridge[5109]: [1/31/2020, 3:24:26 PM] [DenonAVR] No Denon receiver with IP: 192.168.188.11 found in network. Using manual port: 80.

And no new devices in my home app.

The IP address is definitely correct for my AVR-X3200W...

```
http://192.168.188.11:80/goform/formMainZone_MainZoneXmlStatusLite.xml


<?xml version="1.0" encoding="utf-8" ?>
<item>
<Power><value>ON</value></Power>
<InputFuncSelect><value>NET</value></InputFuncSelect>
<VolumeDisplay><value>Absolute</value></VolumeDisplay>
<MasterVolume><value>-29.0</value></MasterVolume>
<Mute><value>off</value></Mute>
</item>
```

**Comment by Martvvliet** [comment]
Yeah that is not really an error but more as information. The older receivers do not support the ssdp discover function as the new receivers with port 8080 do. So it doesn't auto discover, but it will work with the manual port. I will edit the message so it looks more informative.

Did you manually added the receiver after configurating the plugin? You will have to add tv accessories manually in homekit. This is necessary if you want more than one receiver in your home.

**Comment by rbswift** [comment]
Ah thanks. I couldn't find how to add the receiver after configuring the platform device. I don't see anything new in the Home app or when I try to add a device from the bridge. My log just shows this:

`[1/31/2020, 7:00:11 PM] [DenonAVR] pollForUpdates: 192.168.188.11
[1/31/2020, 7:00:11 PM] [DenonAVR] updateReceiverStatus: Lounge Amplifier
[1/31/2020, 7:00:11 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:11 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:11 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:11 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:12 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:12 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:12 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:12 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:13 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:13 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:13 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:13 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:14 PM] [DenonAVR] pollForUpdates: 192.168.188.11
[1/31/2020, 7:00:14 PM] [DenonAVR] updateReceiverStatus: Lounge Amplifier
[1/31/2020, 7:00:14 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:14 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:14 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:14 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:15 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:15 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:15 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:15 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:16 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:16 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:16 PM] [DenonAVR] setupTvService: Lounge Amplifier
[1/31/2020, 7:00:16 PM] [DenonAVR] setupTvService: Lounge Amplifier
`

**Comment by Martvvliet** [comment]
Yeah you go to add accesory and push the `I dont have a code or can't scan` option. You should see the receiver their and you can add it with the same code as you used for homebridge.
Is it working now? Otherwise can you send the log for a longer time? This part looks ok, but it should after some second stop doing the `setupTvService` and start working.

**Comment by rbswift** [comment]
Unfortunately not. I go the` I don't have a code` screen and there are no available accessories to select. I will try to get more log but the `setupTvService` seems to run forever

**Comment by Martvvliet** [comment]
Ok well that is definitely a bug than which I haven't seen yet. Can you post the log from the moment you start it to around 5-10 second later? I can take a look at it maybe later today or the weekend.

**Comment by rbswift** [comment]
```
Jan 31 19:24:22 pi4 homebridge[13453]: [1/31/2020, 7:24:22 PM] Registering platform 'hombridge-denon-heos.DenonAVR'
Jan 31 19:24:24 pi4 homebridge[13453]: [1/31/2020, 7:24:24 PM] [DenonAVR] Initializing DenonAVR platform...
Jan 31 19:24:24 pi4 homebridge[13453]: [1/31/2020, 7:24:24 PM] [DenonAVR] Start receiver with ip: 192.168.188.11
Jan 31 19:24:24 pi4 homebridge[13453]: [1/31/2020, 7:24:24 PM] [DenonAVR] Manual port 80 set: 192.168.188.11
Jan 31 19:24:24 pi4 homebridge[13453]: [1/31/2020, 7:24:24 PM] [DenonAVR] DidFinishLaunching
Jan 31 19:24:27 pi4 homebridge[13453]: [1/31/2020, 7:24:27 PM] [DenonAVR] No Denon receiver with IP: 192.168.188.11 found in network. Using manual port: 80.
Jan 31 19:24:27 pi4 homebridge[13453]: [1/31/2020, 7:24:27 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:27 pi4 homebridge[13453]: [1/31/2020, 7:24:27 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:27 pi4 homebridge[13453]: [1/31/2020, 7:24:27 PM] [DenonAVR] removeCachedAccessory
Jan 31 19:24:27 pi4 homebridge[13453]: [1/31/2020, 7:24:27 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:28 pi4 homebridge[13453]: [1/31/2020, 7:24:28 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:28 pi4 homebridge[13453]: [1/31/2020, 7:24:28 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:28 pi4 homebridge[13453]: [1/31/2020, 7:24:28 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:28 pi4 homebridge[13453]: [1/31/2020, 7:24:28 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:29 pi4 homebridge[13453]: [1/31/2020, 7:24:29 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:29 pi4 homebridge[13453]: [1/31/2020, 7:24:29 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:29 pi4 homebridge[13453]: [1/31/2020, 7:24:29 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:29 pi4 homebridge[13453]: [1/31/2020, 7:24:29 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:30 pi4 homebridge[13453]: [1/31/2020, 7:24:30 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:30 pi4 homebridge[13453]: [1/31/2020, 7:24:30 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:30 pi4 homebridge[13453]: [1/31/2020, 7:24:30 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:30 pi4 homebridge[13453]: [1/31/2020, 7:24:30 PM] [DenonAVR] pollForUpdates: 192.168.188.11
Jan 31 19:24:30 pi4 homebridge[13453]: [1/31/2020, 7:24:30 PM] [DenonAVR] updateReceiverStatus: Lounge Amplifier
Jan 31 19:24:30 pi4 homebridge[13453]: [1/31/2020, 7:24:30 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:31 pi4 homebridge[13453]: [1/31/2020, 7:24:31 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:31 pi4 homebridge[13453]: [1/31/2020, 7:24:31 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:31 pi4 homebridge[13453]: [1/31/2020, 7:24:31 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:31 pi4 homebridge[13453]: [1/31/2020, 7:24:31 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:32 pi4 homebridge[13453]: [1/31/2020, 7:24:32 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:32 pi4 homebridge[13453]: [1/31/2020, 7:24:32 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:32 pi4 homebridge[13453]: [1/31/2020, 7:24:32 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:32 pi4 homebridge[13453]: [1/31/2020, 7:24:32 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:33 pi4 homebridge[13453]: [1/31/2020, 7:24:33 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:33 pi4 homebridge[13453]: [1/31/2020, 7:24:33 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:33 pi4 homebridge[13453]: [1/31/2020, 7:24:33 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:33 pi4 homebridge[13453]: [1/31/2020, 7:24:33 PM] [DenonAVR] pollForUpdates: 192.168.188.11
Jan 31 19:24:33 pi4 homebridge[13453]: [1/31/2020, 7:24:33 PM] [DenonAVR] updateReceiverStatus: Lounge Amplifier
Jan 31 19:24:33 pi4 homebridge[13453]: [1/31/2020, 7:24:33 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:34 pi4 homebridge[13453]: [1/31/2020, 7:24:34 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:34 pi4 homebridge[13453]: [1/31/2020, 7:24:34 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:34 pi4 homebridge[13453]: [1/31/2020, 7:24:34 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:34 pi4 homebridge[13453]: [1/31/2020, 7:24:34 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:35 pi4 homebridge[13453]: [1/31/2020, 7:24:35 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:35 pi4 homebridge[13453]: [1/31/2020, 7:24:35 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:35 pi4 homebridge[13453]: [1/31/2020, 7:24:35 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:35 pi4 homebridge[13453]: [1/31/2020, 7:24:35 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:36 pi4 homebridge[13453]: [1/31/2020, 7:24:36 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:36 pi4 homebridge[13453]: [1/31/2020, 7:24:36 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:36 pi4 homebridge[13453]: [1/31/2020, 7:24:36 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:36 pi4 homebridge[13453]: [1/31/2020, 7:24:36 PM] [DenonAVR] pollForUpdates: 192.168.188.11
Jan 31 19:24:36 pi4 homebridge[13453]: [1/31/2020, 7:24:36 PM] [DenonAVR] updateReceiverStatus: Lounge Amplifier
Jan 31 19:24:36 pi4 homebridge[13453]: [1/31/2020, 7:24:36 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:37 pi4 homebridge[13453]: [1/31/2020, 7:24:37 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:37 pi4 homebridge[13453]: [1/31/2020, 7:24:37 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:37 pi4 homebridge[13453]: [1/31/2020, 7:24:37 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:37 pi4 homebridge[13453]: [1/31/2020, 7:24:37 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:38 pi4 homebridge[13453]: [1/31/2020, 7:24:38 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:38 pi4 homebridge[13453]: [1/31/2020, 7:24:38 PM] [DenonAVR] setupTvService: Lounge Amplifier
Jan 31 19:24:38 pi4 homebridge[13453]: [1/31/2020, 7:24:38 PM] [DenonAVR] setupTvService: Lounge Amplifier

```

**Comment by rbswift** [comment]
```
        {
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "Lounge Amplifier",
                    "ip": "192.168.188.11",
                    "switchInfoMenu": true,
                    "port": "80",
                    "inputs": [
                        {
                            "inputID": "MPLAY",
                            "name": "Media Player"
                        },
                        {
                            "inputID": "Internet Radio",
                            "name": "Internet Radio"
                        },
                        {
                            "inputID": "BT",
                            "name": "Bluetooth"
                        },
                        {
                            "inputID": "Spotify",
                            "name": "Spotify"
                        },
                        {
                            "inputID": "NET",
                            "name": "Airplay"
                        }
                    ]
                }
            ]
        }
```

**Comment by rbswift** [comment]
great - thanks again for your help

**Comment by SirNoble** [comment]
Getting the same error after updating to version 2.1.0.
 [DenonAVR] No Denon receiver with IP: 192.168.0.197 found in network. Using manual port: 80.
Tried port 8080, as well as removing the port.
Still the same issue. 
Config is pretty much the same as above.

**Comment by muzzymate** [comment]
Weighing in that upgrading to the 2.1.0 version also causes my Denon receivers (AVR-X1200W and AVR-1913) to disappear and they do not show up with the "I don't have a code" button. Moving back to homebridge-denon-heos@2.0.8 cause them to reappear.

**Comment by rbswift** [comment]
Ah yes - thanks all - rolling back seems to fix it. I'll do that and then upgrade in due course. Cheers

**Comment by dppeak** [comment]
2.1.0 caused my x1300h to loose connection as well.  Rolled back to 2.0.8 and showed back up.

**Comment by Martvvliet** [comment]
Hmm, don't know why it didn't happen in my setup but found a bug that should cause this issue. I fixed it in 2.1.1, so your receivers should appear again. Sorry for the inconvenience and thank you for reporting. 
If it is still not OK, please let me know. Might need to buy a secondhand non-Heos receiver so I can actually test it on more than my own Heos receiver :/

**Comment by muzzymate** [comment]
Thank you! Yes, 2.1.1 update has my two receivers surviving the upgrade. :-)

Can’t imagine trying to support something you don’t have access to. If you set up a donate button, I’d be happy to kick some dollars over for the cause.

**Comment by ChrWi** [comment]
Ok, 2.1.1 also works again for my Marantz NR1510. Thanks!

**Comment by rbswift** [comment]
Yes that seems to have fixed it. Thanks for working on it so quickly!

**Comment by Martvvliet** [comment]
@muzzymate great to hear. With some help from the issues page, we'll get there. Thank you, will look into it :)

@ChrWi & @rbswift great enjoy :) No problem
