### ISSUE TITLE
No Light Bulb for volume control

### ISSUE THREAD

**Issue by dewoert** [Martvvliet/homebridge-denon-heos#17]
I installed the @latest version today, change my config, but there is no volume control added (Light Bulb)
In the logging I can't see any errors.
Receiver: Denon AVR-X2500H
Config:
`{
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "Denon Receiver",
                    "ip": "192.168.2.5",
                    "switchInfoMenu": true,
                    "port": 8080,
                    "volumeControl": [
                        {
                            "name": "Denon Volume",
                            "ip": "192.168.2.5",
                            "volumeLimit": 60,
                            "port": 8080
                        }
                    ],
                    "inputs": [
                        {
                            "inputID": "SAT/CBL",
                            "name": "KPN TV"
                        },
                        {
                            "inputID": "DVD",
                            "name": "Kodi 4"
                        },
                        {
                            "inputID": "BD",
                            "name": "Apple TV 4K"
                        },
                        {
                            "inputID": "SPOTIFY",
                            "name": "Spotify"
                        },
                        {
                            "inputID": "NET",
                            "name": "HEOS"
                        }
                    ]
                }
            ]
        },`

**Comment by Martvvliet** [comment]
I can see that you added the VolumeControl under the devices. As it is also possible to use this plugin only with switches and not with devices, I made it in such a way that you have to add the volume control outside the switches. So:

```json
{
  "platform": "DenonAVR",
  "pollInterval": 3,
  "devices": [{
    "name": "Denon Receiver",
    "ip": "192.168.2.5",
    "switchInfoMenu": true,
    "port": 8080,
    "inputs": [{
      "inputID": "SAT/CBL",
      "name": "KPN TV"
    }, {
      "inputID": "DVD",
      "name": "Kodi 4"
    }, {
      "inputID": "BD",
      "name": "Apple TV 4K"
    }, {
      "inputID": "SPOTIFY",
      "name": "Spotify"
    }, {
      "inputID": "NET",
      "name": "HEOS"
    }]
  }],
  "volumeControl": [{
      "name": "Denon Volume",
      "ip": "192.168.2.5",
      "volumeLimit": 60,
      "port": 8080
  }]
}
```

**Comment by dewoert** [comment]
Thanks !
Working perfect now.

**Comment by Martvvliet** [comment]
Great enjoy!
