### ISSUE TITLE
Volume bulb not visible

### ISSUE THREAD

**Issue by ChrWi** [Martvvliet/homebridge-denon-heos#18]
I added the volume control after update to 2.2.1, but the control is not shown.
I still have the volume control based on another plugin (marantz-volume) with same settings that works fine.
Any idea?

**Comment by Martvvliet** [comment]
Can you post your config file, Than I will check it.

**Comment by ChrWi** [comment]
Below the relevant config wrt both plugins.

`{
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "AVR-Remote",
                    "ip": "192.168.78.6",
                    "switchInfoMenu": true,
                    "port": 8080,
                    "volumeControl": [
                        {
                            "name": "Receiver Volume",
                            "ip": "192.168.78.6:8080",
                            "volumeLimit": 50,
                            "port": 8080
                        }
                    ],
                    "inputs": [
                        {
                            "inputID": "SAT/CBL",
                            "name": "TV"
                        },
                        {
                            "inputID": "BD",
                            "name": "CD/DVD"
                        },
                        {
                            "inputID": "MPLAY",
                            "name": "Mediaserver"
                        },
                        {
                            "inputID": "Internet Radio",
                            "name": "Internet Radio"
                        },
                        {
                            "inputID": "NET",
                            "name": "Airplay"
                        }
                    ]
                }
            ]
        }
    ],
    "accessories": [
        {
            "accessory": "marantz-volume",
            "name": "AVR-Volume",
            "host": "192.168.78.6:8080",
            "maxVolume": 50,
            "controlPower": true
        }
    ]`

**Comment by muzzymate** [comment]
Wondering out loud if it has to do with the volumeControl box and the IP address specified. 

            "ip": "192.168.78.6:8080",
            "port": 8080

should be

            "ip": "192.168.78.6",
            "port": 8080

**Comment by ChrWi** [comment]
You are right, but interestingly no difference after change/restart.
I removed the marantz-volume accessory, but no new bulb afterwards.
Any cache problem or similar? Device and Inputs are running fine.
But it's not a big problem for me as I can continue using the separate plugin for volume control.

**Comment by ChrWi** [comment]
You are totally right - it works now!

**Comment by Martvvliet** [comment]
Great enjoy :)

**Comment by ChrWi** [comment]
Volume bulb is gone after updating to version 2.36. (was fine with 2.34) Looking into the changelog - what kind of fix have you implemented?

**Comment by Martvvliet** [comment]
Hmm weird. I added support for receivers without absolute/relative volume control functionality. Can you turn on Debug mode and send me the log? My setup still has the volume bulb, so no clue why this happens

**Comment by ChrWi** [comment]
Strange - I removed the accessories cache, after homebridge restart the volume bulb is back. Never did this before after updating any homebridge plugin. But it works now!

[iOS]

**Comment by Martvvliet** [comment]
Hmm. Can’t think of a reason why this should be necessary. Will take a look if I can find something. For now I will close this issue. Thank you and please let me know if you have other issues
