### ISSUE TITLE
Reading current status issue 2.3.0

### ISSUE THREAD

**Issue by muzzymate** [Martvvliet/homebridge-denon-heos#21]
I have a Denon AVR-1913 and a Denon AVR-X1200W. Both utilize port 80 for HTTP control and is configured in the json file.

After upgrading to 2.3.0 and 2.3.1, the tiles in the Home app do not properly reflect the status of the receiver. For example, if the receiver is on and set to the AUX input, the tile will reflect that the receiver is off. Volume control shows as off as well.

If I tap the tile, the tile in the Home app will then show that the receiver is on. Inputs and volume will switch correctly. However, if I make a change on the receiver itself, that change is never reflected in the home tile app, even if I force close and reopen the Home app.

Going back to version 2.2.1, the tiles will properly reflect the current state of the input and volume level of the receiver, regardless if I change it on the receiver or the Home app.

**Comment by Martvvliet** [comment]
Hmm. I think I found it. It looked to be the case when setting the port manual. It will probably work if you set it to auto, as I fixed the auto port detection for port 80 too (I think). But in 2.3.3 it should also be fixed with manual setting the port. Thank you for reporting the issue.

**Comment by muzzymate** [comment]
Yeah, looks like in version 2.3.4 auto port detection is working for me/us? with early 2010 Denon receivers. I no longer have the port specified in my config.json file and the below message being logged to the console. Nice work! Thank you! :-)

[2/18/2020, 12:46:02 PM] [DenonAVR] Using http control with on 80 with receiver: 10.0.1.246
[2/18/2020, 12:46:02 PM] [DenonAVR] Using http control with on 80 with receiver: 10.0.1.245

**Comment by Martvvliet** [comment]
Great. Good to know its working finally:)
