### ISSUE TITLE
Volume control is displayed as lamp brightness in Home App

### ISSUE THREAD

**Issue by mrmaximas** [Martvvliet/homebridge-denon-heos#22]
![413CDA67-B043-44D1-BAF3-F1000484360B](https://user-images.githubusercontent.com/61165387/75043995-f0055200-54d1-11ea-8f39-0fa36dcb8c1e.png)

**Comment by Martvvliet** [comment]
Yes, that is how it works. You can control the volume with the remote widget by pressing the volume buttons. This will increase/decrease relative to the current volume. As there is no support for an absolute volume level, I have added it as a lamp with its brightness. This way you can also control the volume through Siri. You can choose a lamp icon that looks a bit like a TV, but sadly enough, this is the only option as long as Apple doesn't support absolute volume control.
