### ISSUE TITLE
Request for additional features :-)

### ISSUE THREAD

**Issue by bmonninkhof** [Martvvliet/homebridge-denon-heos#26]
Love this plugin for Homebridge, it could be even better with some additional features:
- soundmode control / switches https://github.com/ishockwave/homebridge-denon-soundmode
- actually play an online Chanel with a switch, like in the HEOS app
- control multiroom zones

In this repository is al lot you probably use? https://github.com/scarface-4711/denonavr

**Comment by Martvvliet** [comment]
Thank you for your feedback. Multiroom support is the first thing I wanted to add so that one should arrive pretty soon. I look into the other features :) Should be that hard indeed.

**Comment by vincent0794** [comment]
Thanks for the great plugin. Am keen to see multiform support, although the first part of that I'd personally find most useful is a simple "All Zone Stereo" on/off switch (https://denon.custhelp.com/app/answers/detail/a_id/1804/~/all-zone-stereo ).

As an FYI, I've used a simple http-switch to swap my X3600H (Denon AVR) between 9.1ch (when I want to watch movies with full surround) and 7.1ch+zone2 (when I want to listen to music in one or two or both zones). This is otherwise a pain to do without multiple menu/button selections.
        {
            "accessory": "HTTP-SWITCH",
            "name": "Add Zone2",
            "switchType": "stateful",
            "debug": false,
            "onUrl": "https://192.168.1.93:10443/ajax/speakers/set_config?type=2&data=%3CAmpAssign%3E%3CAssignMode%3E2%3C%2FAssignMode%3E%3C%2FAmpAssign%3E&_=1587642388217",
            "offUrl": "https://192.168.1.93:10443/ajax/speakers/set_config?type=2&data=%3CAmpAssign%3E%3CAssignMode%3E1%3C%2FAssignMode%3E%3C%2FAmpAssign%3E&_=1587642388217",
            "statusUrl": "https://192.168.1.93:10443/ajax/speakers/get_config?type=2",
            "statusPattern": ".*<AssignMode>2</AssignMode>.*"
        }

**Comment by Martvvliet** [comment]
@bmonninkhof Second zone support is added. Can you let me know if it is working as expected?

**Comment by bmonninkhof** [comment]
Mart,

Ja werkt! Zal het nog even beter gaan testen, maar het begin is er!!! Too

Met vriendelijke groet, Brian

Verstuurd vanaf mijn iPhone

Op 5 mei 2020 om 14:53 heeft Martvvliet <notifications@github.com> het volgende geschreven:

﻿

@bmonninkhof<https://github.com/bmonninkhof> Second zone support is added. Can you let me know if it is working as expected?

**Comment by Martvvliet** [comment]
@bmonninkhof Top dank voor het testen in ieder geval. Ik hoor het graag als er nog issues zijn.

**Comment by bmonninkhof** [comment]
Mart,

Ben nog steeds groot fan van jouw plugin. Echt tot nu toe de beste plugin voor de Denon 🙂 👍

Ter info, ik heb de Denon AVR-X2500H met twee zones. Een voor de woonkamer en een voor de badkamer.

Volumeknop:
Wanneer de AVR niet aan staat en ik wil deze knop gebruiken dan schakelt deze de knop naar een paar seconden weer uit. Waarschijnlijk omdat je het volume alleen kunt bedienen wanneer de AVR aan staat?

HomeKit:
In mijn geval komen na een herstart slechts drie knoppen in beeld, namelijk de "aan/uit-schakelaar AppleTV" en "Volume badkamer" en "Volume woonkamer". Na wat herstarts komt de rest ook in beeld, maar echt betrouwbaar gaat dit nog niet. Met name de remote komt niet in beeld. Zie de screenshots

Onderstaand screenshot komt uit de HomeBridge omgeving, waarvan alleen de laatste vier knoppen in homekit terecht komen.

[cid:a56eb3e7-14f3-4daf-996e-33247a0bca11]
En onderstaand het resultaat in homekit
[cid:9a596f4d-4f52-4061-bb74-ff36129edbb0]

Instellingen:
Ik heb er toch voor gekozen om de poorten allemaal in te vullen en niet op auto te zetten. Ik heb het idee dat het daardoor stabieler wordt.

mijn instellingen:
{
                    "name": "Denon AVR afstandsbediening boven",
                    "ip": "192.168.1.180",
                    "port": "8080",
                    "zone": 2,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "NET",
                            "name": "HEOS Music",
                            "defaultVolume": 40
                        }
                    ]
                },
                {
                    "name": "Denon AVR afstandsbediening beneden",
                    "ip": "192.168.1.180",
                    "port": "8080",
                    "zone": 1,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "MPLAY",
                            "name": "Apple TV",
                            "defaultVolume": 50
                        },
                        {
                            "inputID": "DVD",
                            "name": "DVD",
                            "defaultVolume": 50
                        },
                        {
                            "inputID": "NET",
                            "name": "HEOS music",
                            "defaultVolume": 40
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "Heos Muziek",
                    "ip": "192.168.1.180",
                    "port": "8080",
                    "zone": 1,
                    "inputID": "NET",
                    "pollAllInput": false,
                    "defaultVolume": 40
                },
                {
                    "name": "AppleTV",
                    "ip": "192.168.1.180",
                    "port": "8080",
                    "zone": 1,
                    "inputID": "MPLAY",
                    "pollAllInput": false,
                    "defaultVolume": 50
                }
            ],
            "volumeControl": [
                {
                    "name": "Volume woonkamer",
                    "ip": "192.168.1.180",
                    "zone": 1,
                    "port": "8080",
                    "volumeLimit": 75
                },
                {
                    "name": "Volume badkamer",
                    "ip": "192.168.1.180",
                    "zone": 2,
                    "port": "8080",
                    "volumeLimit": 60
                }
            ],
            "platform": "DenonAVR"
        },

Overigens heb ik nog wel een idee voor een toekomstige uitbreiding van jouw plugin. Dat je favorieten in de HEOS app kunt kiezen in een menu.

m.v.g. Brian Monninkhof


________________________________
Van: Martvvliet <notifications@github.com>
Verzonden: vrijdag 8 mei 2020 19:43
Aan: Martvvliet/homebridge-denon-heos <homebridge-denon-heos@noreply.github.com>
CC: bmonninkhof <bmonninkhof@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Martvvliet/homebridge-denon-heos] Request for additional features :-) (#26)


@bmonninkhof<https://github.com/bmonninkhof> Top dank voor het testen in ieder geval. Ik hoor het graag als er nog issues zijn.

**Comment by bmonninkhof** [comment]
Mart,

Zo weer iets verder en je zult wel hebben gedacht... "lezen man... je moet de afstandsbedieningen toevoegen aan Woning". Tja... was ik even vergeten, maar ik heb nu alle knoppen werkend in Woning.
Wat ik merk dat het standaard geluidsniveau niet wordt bepaald door jouw plugin, maar door de Denon AVR instelling. Standaard had ik het "Volume bij aanzetten" op 20 staan. Ik heb Mute en Laatste geprobeerd, maar dit maakt vooralsnog geen verschil uit. De AVR bepaald kennelijk het niveau bij de "remote knoppen". Bij de Switches werkt de volume voorkeur wel!

Groeten Brian

[cid:0acb9f13-f499-4e4b-bf9a-23247f30f2e1]
________________________________
Van: Brian Monninkhof <bmonninkhof@hotmail.com>
Verzonden: donderdag 14 mei 2020 12:08
Aan: Martvvliet/homebridge-denon-heos <reply@reply.github.com>
Onderwerp: Re: [Martvvliet/homebridge-denon-heos] Request for additional features :-) (#26)

Mart,

Ben nog steeds groot fan van jouw plugin. Echt tot nu toe de beste plugin voor de Denon 🙂 👍

Ter info, ik heb de Denon AVR-X2500H met twee zones. Een voor de woonkamer en een voor de badkamer.

Volumeknop:
Wanneer de AVR niet aan staat en ik wil deze knop gebruiken dan schakelt deze de knop naar een paar seconden weer uit. Waarschijnlijk omdat je het volume alleen kunt bedienen wanneer de AVR aan staat?

HomeKit:
In mijn geval komen na een herstart slechts drie knoppen in beeld, namelijk de "aan/uit-schakelaar AppleTV" en "Volume badkamer" en "Volume woonkamer". Na wat herstarts komt de rest ook in beeld, maar echt betrouwbaar gaat dit nog niet. Met name de remote komt niet in beeld. Zie de screenshots

Onderstaand screenshot komt uit de HomeBridge omgeving, waarvan alleen de laatste vier knoppen in homekit terecht komen.

[cid:a56eb3e7-14f3-4daf-996e-33247a0bca11]
En onderstaand het resultaat in homekit
[cid:9a596f4d-4f52-4061-bb74-ff36129edbb0]

Instellingen:
Ik heb er toch voor gekozen om de poorten allemaal in te vullen en niet op auto te zetten. Ik heb het idee dat het daardoor stabieler wordt.

mijn instellingen:
{
                    "name": "Denon AVR afstandsbediening boven",
                    "ip": "192.168.1.180",
                    "port": "8080",
                    "zone": 2,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "NET",
                            "name": "HEOS Music",
                            "defaultVolume": 40
                        }
                    ]
                },
                {
                    "name": "Denon AVR afstandsbediening beneden",
                    "ip": "192.168.1.180",
                    "port": "8080",
                    "zone": 1,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "MPLAY",
                            "name": "Apple TV",
                            "defaultVolume": 50
                        },
                        {
                            "inputID": "DVD",
                            "name": "DVD",
                            "defaultVolume": 50
                        },
                        {
                            "inputID": "NET",
                            "name": "HEOS music",
                            "defaultVolume": 40
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "Heos Muziek",
                    "ip": "192.168.1.180",
                    "port": "8080",
                    "zone": 1,
                    "inputID": "NET",
                    "pollAllInput": false,
                    "defaultVolume": 40
                },
                {
                    "name": "AppleTV",
                    "ip": "192.168.1.180",
                    "port": "8080",
                    "zone": 1,
                    "inputID": "MPLAY",
                    "pollAllInput": false,
                    "defaultVolume": 50
                }
            ],
            "volumeControl": [
                {
                    "name": "Volume woonkamer",
                    "ip": "192.168.1.180",
                    "zone": 1,
                    "port": "8080",
                    "volumeLimit": 75
                },
                {
                    "name": "Volume badkamer",
                    "ip": "192.168.1.180",
                    "zone": 2,
                    "port": "8080",
                    "volumeLimit": 60
                }
            ],
            "platform": "DenonAVR"
        },

Overigens heb ik nog wel een idee voor een toekomstige uitbreiding van jouw plugin. Dat je favorieten in de HEOS app kunt kiezen in een menu.

m.v.g. Brian Monninkhof


________________________________
Van: Martvvliet <notifications@github.com>
Verzonden: vrijdag 8 mei 2020 19:43
Aan: Martvvliet/homebridge-denon-heos <homebridge-denon-heos@noreply.github.com>
CC: bmonninkhof <bmonninkhof@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Martvvliet/homebridge-denon-heos] Request for additional features :-) (#26)


@bmonninkhof<https://github.com/bmonninkhof> Top dank voor het testen in ieder geval. Ik hoor het graag als er nog issues zijn.

**Comment by Martvvliet** [comment]
Hi Brian, Haha geen issue. kan gebeuren, fijn dat het in ieder geval werkt :). Ik ga nog even kijken naar die default volume van de inputs, aangezien deze wel zou moeten werken. Ik kom er nog even op terug. Thanks in ieder geval voor de feedback.

**Comment by Martvvliet** [comment]
In versie 2.7.1 kan je een default inputID selecteren. Als je deze erbij zet zal die automatisch die input selecteren bij het aanzetten van de receiver en de daarbij behorende default volume wordt dan ook geselecteerd.

**Comment by bmonninkhof** [comment]
Mart,

Direct ingesteld 🙂
Groetjes Brian
________________________________
Van: Martvvliet <notifications@github.com>
Verzonden: maandag 18 mei 2020 19:39
Aan: Martvvliet/homebridge-denon-heos <homebridge-denon-heos@noreply.github.com>
CC: bmonninkhof <bmonninkhof@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Martvvliet/homebridge-denon-heos] Request for additional features :-) (#26)


In versie 2.7.1 kan je een default inputID selecteren. Als je deze erbij zet zal die automatisch die input selecteren bij het aanzetten van de receiver en de daarbij behorende default volume wordt dan ook geselecteerd.

**Comment by Martvvliet** [comment]
Hi Brian, werkt alles nu naar behoren? Dan kan ik dit issue sluiten :)

**Comment by bmonninkhof** [comment]
Hoi Mart,


  *   volumeknoppen aanzetten zonder een andere knop werkt niet, die gaat dan vanzelf weer uit. Maar goed, op zich geen probleem
  *   volume preset van de Remote werkt WEL!

top werk!!

Groetjes Brian

________________________________
Van: Martvvliet <notifications@github.com>
Verzonden: donderdag 21 mei 2020 09:39
Aan: Martvvliet/homebridge-denon-heos <homebridge-denon-heos@noreply.github.com>
CC: bmonninkhof <bmonninkhof@hotmail.com>; Mention <mention@noreply.github.com>
Onderwerp: Re: [Martvvliet/homebridge-denon-heos] Request for additional features :-) (#26)


Hi Brian, werkt alles nu naar behoren? Dan kan ik dit issue sluiten :)

**Comment by Martvvliet** [comment]
Hi Brian,
Top dan sluit ik deze. De volumeknoppen zullen alleen reageren als de versterker al is aangezet. Als dit alsnog niet werkt terwijl de versterker aan staat hoor ik het graag. 

In ieder geval veel plezier ermee.

Groet,
