### ISSUE TITLE
Home App requests an 8 digit code

### ISSUE THREAD

**Issue by galzil** [Martvvliet/homebridge-denon-heos#28]
Great plugin, thanks.
It works great as switches, and now I'm trying to add my receiver (Marantz SR5012) as a Device (TV) but the Home app requests an 8 digit code.
Is there a defualt code?

**Comment by Martvvliet** [comment]
@galzil Thank you. You can use the same code you used to add homebridge.

**Comment by galzil** [comment]
Thanks

**Comment by galzil** [comment]
The homebridge 8 digit code was used to add the TV device
