### ISSUE TITLE
Pick volume with fan control

### ISSUE THREAD

**Issue by neres909** [Martvvliet/homebridge-denon-heos#30]
Hey, first of all - great work! Much appreciated.
To the issue now - would it be possible to change (or make it an option) to use fan control as volume control for this plugin? This way voice commands as “turn off/on the lights” wouldn’t affect avr’s volume.

**Comment by Martvvliet** [comment]
Thnx for input. Will check if I can make it an option :)

**Comment by Martvvliet** [comment]
@neres909 in version 2.8.0, you can set a`"volumeAsFan": true` in the volumeControl. This will change the volumeControl from a lightbulb to a fan. Example Json can be found on the main page

**Comment by neres909** [comment]
Works like a charm! Thank you @Martvvliet :)
