### ISSUE TITLE
Problem with Denon x2400h

### ISSUE THREAD

**Issue by maikerdmann97** [Martvvliet/homebridge-denon-heos#35]
Hey,
I don't get the plugin to work.
I use hoobs.
My config is 

{
            "platform": "DenonAVR",
            "plugin_map": {
                "plugin_name": "homebridge-denon-heos"
            },
            "pollInterval": 3,
            "debugToInfo": false,
            "devices": [
                {
                    "name": "Denon Receiver",
                    "ip": "192.168.178.30",
                    "inputs": [
                        {
                            "inputID": "BD",
                            "name": "XBOX",
                            "defaultVolume": 35
                        }
                    ]
                }
            ]
        }

The Receiver doesn't even show up in my HomeKit.

Would be nice if you can help me.

**Comment by Martvvliet** [comment]
Is it fixed?

**Comment by maikerdmann97** [comment]
Hoops doesn't say in their logs, that I need to add with the code.
and than I had a problem that it doesn't response but the solution was to remove the accessory and the add it again

**Comment by maikerdmann97** [comment]
*Hoobs

**Comment by Martvvliet** [comment]
Ok well enjoy :)
