### ISSUE TITLE
Hombridge stopps working after new plugin-update

### ISSUE THREAD

**Issue by MasterofKungfu9999** [Martvvliet/homebridge-denon-heos#36]
After the latest update of the plugin, hombridge stops.

Here ist my configuration and the logs:

{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWYHHK5",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "de",
        "temp_units": "celsius",
        "country_code": "DE",
        "postal_code": "32130"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "5F:8E:1A:C3:39:9E"
    },
    "description": "",
    "ports": {},
    "accessories": [],
    "platforms": [
        {
            "platform": "BlinkSecurityPlatform",
            "name": "Blink System",
            "username": "",
            "password": "",
            "discovery": false,
            "plugin_map": {
                "plugin_name": "homebridge-blinkcameras"
            }
        },
        {
            "platform": "WeatherPlus",
            "service": "darksky",
            "key": "",
            "locationGeo": [
                52.1416496,
                8.5580984
            ],
            "interval": 4,
            "conditionCategory": "detailed",
            "forecast": [
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7
            ],
            "language": "de",
            "nameNow": "",
            "plugin_map": {
                "plugin_name": "homebridge-weather-plus"
            },
            "units": "si"
        },
        {
            "platform": "Hue",
            "plugin_map": {
                "plugin_name": "hue"
            },
            "name": "Hue",
            "forceCt": true,
            "nativeHomeKitLights": true,
            "nativeHomeKitSensors": false,
            "nupnp": true,
            "resource": false,
            "users": {
                ""
            },
            "lights": true,
            "wallSwitch": true,
            "heartrate": 2,
            "anyOn": true,
            "hosts": "192.168.13.48",
            "forceHttp": true
        },
        {
            "platform": "FritzPlatform",
            "devices": {
                "FRITZ!Box 7590": {
                    "active": true,
                    "host": "192.168.13.1",
                    "port": 49000,
                    "username": "admin",
                    "password": "",
                    "type": "dsl",
                    "master": true,
                    "mesh": true,
                    "readOnly": false,
                    "options": {
                        "reconnect": true,
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "aw": [
                            true,
                            false
                        ],
                        "deflection": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ],
                        "lock": [
                            true,
                            false
                        ]
                    }
                },
                "FRITZ-Repeater-unten": {
                    "active": true,
                    "host": "192.168.13.23",
                    "port": 49000,
                    "username": "admin",
                    "password": "",
                    "type": "repeater",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ]
                    }
                },
                "FRITZ!Repeater oben": {
                    "active": true,
                    "host": "192.168.13.25",
                    "port": 49000,
                    "username": "admin",
                    "password": "",
                    "type": "repeater",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ]
                    }
                },
                "FRITZ!Repeater 2400": {
                    "active": true,
                    "host": "192.168.13.54",
                    "port": 49000,
                    "username": "admin",
                    "password": "",
                    "type": "repeater",
                    "readOnly": false,
                    "options": {
                        "wifi2": [
                            true,
                            false
                        ],
                        "wifi5": [
                            true,
                            false
                        ],
                        "wifiGuest": [
                            true,
                            false
                        ],
                        "wps": [
                            true,
                            false
                        ],
                        "led": [
                            true,
                            false
                        ]
                    }
                }
            },
            "smarthome": {
                "Test Contact Sensor": {
                    "active": false,
                    "ain": "01234567890",
                    "devType": "contact"
                },
                "Test Thermostat Device": {
                    "active": false,
                    "ain": "01234567890",
                    "heatValue": 5,
                    "coolValue": 5,
                    "windowSensor": false,
                    "devType": "thermostat"
                },
                "Test Outlet Device": {
                    "active": false,
                    "ain": "01234567890",
                    "tempSensor": false,
                    "devType": "switch"
                }
            },
            "callmonitor": {
                "active": false,
                "ip": "0.0.0.0",
                "port": 1012
            },
            "presence": {
                "user": [
                    {
                        "active": true,
                        "name": "",
                        "address": "192.168.13.39"
                    }
                ],
                "anyone": true,
                "offDelay": 10,
                "onDelay": 10,
                "ping": false
            },
            "wol": [
                {
                    "active": false,
                    "name": "Test Device",
                    "address": "00:00:00:00:00:00"
                }
            ],
            "phoneBook": {
                "active": false
            },
            "alarm": {
                "active": false,
                "duration": 30
            },
            "wakeup": {
                "active": false,
                "duration": 30
            },
            "ringlock": {
                "active": false,
                "DECTphones": 1,
                "start": "11:00",
                "end": "22:00"
            },
            "broadband": {
                "active": false,
                "measureTime": 5
            },
            "extReboot": {
                "active": false
            },
            "telegram": {
                "active": false
            },
            "polling": 10,
            "timeout": 10,
            "clearCache": false,
            "debug": false,
            "disableAutoSearch": true,
            "disableAutoConfig": true,
            "plugin_map": {
                "plugin_name": "homebridge-fritz-platform"
            }
        },
        {
            "platform": "OpenWebIfTv",
            "plugin_map": {
                "plugin_name": "homebridge-openwebif-tv"
            }
        },
        {
            "platform": "DenonAVR",
            "plugin_map": {
                "plugin_name": "homebridge-denon-heos"
            },
            "debugToInfo": false,
            "devices": [
                {
                    "name": "Marantz Receiver",
                    "ip": "192.168.13.43",
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "SAT/CBL",
                            "name": "VU+",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "MPLAY",
                            "name": "Apple TV",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "SPOTIFY",
                            "name": "Spotify",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "BD",
                            "name": "Blu-Ray",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "TV",
                            "name": "TV"
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "AVR on Apple TV",
                    "ip": "192.168.13.43",
                    "port": 8080,
                    "inputID": "MPLAY",
                    "pollAllInput": false
                },
                {
                    "name": "AVR on VU+",
                    "ip": "192.168.13.43",
                    "port": 8080,
                    "inputID": "SAT/CBL",
                    "defaultVolume": 45,
                    "pollAllInput": false
                },
                {
                    "name": "AVR on BlueRay",
                    "ip": "192.168.13.43",
                    "port": 8080,
                    "inputID": "BD",
                    "defaultVolume": 45,
                    "pollAllInput": false
                }
            ],
            "volumeControl": [
                {
                    "name": "Receiver Volume",
                    "ip": "192.168.13.43",
                    "volumeLimit": 60,
                    "port": 8080
                }
            ],
            "pollInterval": 3
        }
    ]
}

[logs(2).txt](https://github.com/Martvvliet/homebridge-denon-heos/files/4556791/logs.2.txt)
[logs(3).txt](https://github.com/Martvvliet/homebridge-denon-heos/files/4556799/logs.3.txt)

**Comment by Martvvliet** [comment]
@MasterofKungfu9999 thank you for sending the debug logs.
Did you come from 2.5.x or from 2.4.x or lower? Can you try to change the name of the AVR on Apple TV to AVR on Apple TV2 and send the log again? It has an AVR on Apple TV registered, which should not be the case.
Another option is to temporarily remove the switches. Startup, so it will remove the cached accessories. When you add them again, it should work.

**Comment by MasterofKungfu9999** [comment]
I cam from 2.5.x. I have tried your changes but homebridge stops working.
Removing the switches doesn't bring success

[logs(5).txt](https://github.com/Martvvliet/homebridge-denon-heos/files/4557009/logs.5.txt)

**Comment by Martvvliet** [comment]
And if you go back to version 2.5.2? Does that solve the issue?

**Comment by MasterofKungfu9999** [comment]
i cant't go back, because i'm using Hoobs an there is only the newest version that i can install

**Comment by Martvvliet** [comment]
I just pushed version 2.5.4. It might be fixed. Can you test it for me?

**Comment by MasterofKungfu9999** [comment]
I've tested it and it works fine

**Comment by Martvvliet** [comment]
ok great. So everything is up and running again? Sorry for the inconvenience :(

**Comment by MasterofKungfu9999** [comment]
Yes i think so, the devic, switches and volume control are shown in Homekit

**Comment by Martvvliet** [comment]
oke great. Thanks for posting issue :) will close this one now
