### ISSUE TITLE
Volume setting beyond lightbulbs

### ISSUE THREAD

**Issue by rbswift** [Martvvliet/homebridge-denon-heos#38]
Firstly, thanks for a great plug-in!

I noticed homebridge now supports a few new types including "Speaker", "SmartSpeaker" and "TelevisionSpeaker". Could any of these function as a better way to control volume than the lightbulb approach? I see the last two both have 0-100 volume characteristics so that looks quite promising.

I know second zones are also on the roadmap. I have two zones and I'm really looking forward to the day when I can easily independently set the zone input sources and volumes via homebridge without any clunky workarounds.

Cheers

**Comment by Martvvliet** [comment]
@rbswift Thank you for the information. The TelevisionSpeaker is integrated when you add the receiver as TV service. This means that you can control the volume through the remote widget. As far as I know the Speaker option is the same as how the airplay 2 of Denon is integrated. You just see it, but can't do anything with it. SmartSpeaker I don't know. Will take a look at that and verify what I said on the other two. Maybe something has changed. Will come back on this.

**Comment by rbswift** [comment]
Thanks for this. Fingers crossed SmartSpeaker will be useful. In HAP-NodeJS, SmartSpeaker does have a 0-100% volume characteristic so that is promising but I guess it is a case of whether the Apple Home app actually exposes that characteristic. Curiously, and frustratingly, Apple seems keen to keep volume control away from HomeKit - perhaps to avoid undermining their Airplay protocol?

**Comment by Martvvliet** [comment]
Yeah did some research and it only works if you also have airplay 2 support. So this should actually be something that Denon can implement themselves. Will close this issue for now and will implement if there is an update :) thank you for posting the issue.;
