### ISSUE TITLE
NET input no sound

### ISSUE THREAD

**Issue by rinoronie** [Martvvliet/homebridge-denon-heos#40]
I add a switch with NET input, but Internet radio not start play automatically
In I switch with remote controller on internet radio, it start play the last radio station automatically
If I switch on NET input and then I push PLAY button on remote controller -> Music :)

Why?

**Comment by Martvvliet** [comment]
I’m not sure why. Are you sure it is the same input? You can check what the correct input is with the link I posted in the readme.

**Comment by rinoronie** [comment]
The input is correct, 
On display I see: Heos Music and then TuneIn Internet.
With remote command on display I see:
Heos Music and the “ the name of last radio channel”

**Comment by Martvvliet** [comment]
It might be the case that it gets an extra command through the Heos communication to start the radio. Not sure how that works though. You have two different ways of sending commands. The Heos commands are not integrated.

**Comment by rinoronie** [comment]
I think just send the “play” command

**Comment by Martvvliet** [comment]
I will take a look at it :)

**Comment by rinoronie** [comment]
thanks

**Comment by Martvvliet** [comment]
Can't change anything on this for you sorry. Will close this issue now.
