### ISSUE TITLE
Input Selection using TV Accessory 

### ISSUE THREAD

**Issue by adamgoldman** [Martvvliet/homebridge-denon-heos#42]
Hello,

I am using this on Marantz NR170 and most if not all functionality is as described in the documentation. 

However > I cannot select certain inputs. 

For example: If I turn everything on and the input is CBL/SAT > When I change to another input > AUX1 > The input changes to AUX1 (as expected) BUT - I cannot change back to CBL/SAT input. There are only 3 inputs that work selecting back and forth, all others not working.

Additional Note: I tried with switches, same behaviour, however it does succeed in setting the defaultVolume param on ALL inputs.

Any insight would be helpuful.

Thanks

**Comment by adamgoldman** [comment]
EDIT: Solved for Marantz inputs label incorrectly.

**Comment by Martvvliet** [comment]
Ok, you discovered the correct ones through the link I added in the readme? Good to know everything is working :) enjoy
