### ISSUE TITLE
New Request: Control a remote wifi switch for subwoofer

### ISSUE THREAD

**Issue by rinoronie** [Martvvliet/homebridge-denon-heos#43]
My subwoofer in standby consumes 10W (too much)
Is it possible to command a shelly1 or sonoff (http command) to remove power when the denon is turned off and power on it when the denon is turned on?

Thanks

**Comment by Martvvliet** [comment]
@rinoronie Thank you for your input. 10W is indeed a lot. Have you tried to do this already by using an HTTP command plugin and adding some automations? I think this should do exactly what you want and this feature is quite far outside the 'control of a Denon receiver'.

**Comment by rinoronie** [comment]
Thanks
I think anyone who has a denon could have the same problem
How do I know if the denon is on?

**Comment by Martvvliet** [comment]
You can add automations that if the Denon turn on/off you can turn on/off the switch that controls your subwoofer. It is quite easy.

**Comment by rinoronie** [comment]
An Home (apple) automation? Ah ok it is easy...
But I dont’t have an apple hib domestic and I don’t do automation.

I has think that use the raspberry

**Comment by Martvvliet** [comment]
Ok can’t help you with that sorry. Maybe you can buy an old iPad or something to use as home hub or an Apple TV. Good luck :)
