### ISSUE TITLE
Enhancement: Add Delay to select source

### ISSUE THREAD

**Issue by GerSant** [Martvvliet/homebridge-denon-heos#44]
Sometimes, when i use the accessories generated by this plugin in scenes, the selected input in the scene don't apply, for a reason that in don't known. Maybe if the Power-On command follow by a delayed input select solve the problem. Something like:

`"inputs": [
            {
              "inputID": "SAT/CBL",
              "name": "MiBox 4K",
              "defaultVolume": 50,
              "waitTime": 0.5
            },`

Thanks

**Comment by Martvvliet** [comment]
Hi Gersant, this is not that easy, as it than also happens when you don’t want the delay. You can add switches just for using in scenes. This way you don’t have issues with the delays

**Comment by Martvvliet** [comment]
Will close this issue. Won't add this to the config as you can add these sort of delays through the shortcuts script, which I think is a better solution as you only have the delay when you actually want it. Good luck
