### ISSUE TITLE
Marantz volume buttons keep resetting room placement on homebridge server restart

### ISSUE THREAD

**Issue by tomiy1** [Martvvliet/homebridge-denon-heos#46]
Hi Martvvliet,

I wasnt sure how else to contact you but I needed some support for this plugin as I'm having some weird issues at the moment. Whenever I restart my homebridge server the volume items in "Home" keep resetting their "room" which makes it a pain to change everytime. Any help/direction would be greatly appreciated!

Thank you!
Tomer

**Comment by tomiy1** [comment]
For added context, here is what i have in my config.json for your plugin:

        {
            "debugToInfo": false,
            "devices": [
                {
                    "name": "NR1607 Bedroom",
                    "ip": "192.168.1.143",
                    "zone": 1,
                    "switchInfoMenu": true
                },
                {
                    "name": "NR1607 Bathroom",
                    "ip": "192.168.1.143",
                    "zone": 2,
                    "switchInfoMenu": true
                },
                {
                    "name": "SR5013",
                    "ip": "192.168.1.141",
                    "zone": 1,
                    "switchInfoMenu": true
                },
                {
                    "name": "NR1607 Family",
                    "ip": "192.168.1.142",
                    "zone": 1,
                    "switchInfoMenu": true
                },
                {
                    "name": "NR1607 Patio",
                    "ip": "192.168.1.142",
                    "zone": 2,
                    "switchInfoMenu": true
                }
            ],
            "volumeControl": [
                {
                    "name": "NR1607 Vol Bedroom",
                    "ip": "192.168.1.143",
                    "zone": 1,
                    "volumeLimit": 60
                },
                {
                    "name": "NR1607 Vol Bathroom",
                    "ip": "192.168.1.143",
                    "zone": 2,
                    "volumeLimit": 60
                },
                {
                    "name": "SR5013 Volume 2",
                    "ip": "192.168.1.141",
                    "zone": 1,
                    "volumeLimit": 60
                },
                {
                    "name": "NR1607 Vol Family",
                    "ip": "192.168.1.142",
                    "zone": 1,
                    "volumeLimit": 60
                },
                {
                    "name": "NR1607 Vol Patio",
                    "ip": "192.168.1.142",
                    "zone": 2,
                    "volumeLimit": 60
                }
            ],
            "platform": "DenonAVR"
        },

**Comment by Martvvliet** [comment]
@tomiy1 I made some changes to the way the cached accessories are handled. This means that you will have to rechange the volumeControl blocks ones more, but it might also be fixed after that. Can you verify?

**Comment by Martvvliet** [comment]
As discussed on the other channel. It is fixed with the latest update 2.8.2. Will close this now.
