### ISSUE TITLE
Re-adding accessory after plugin changes

### ISSUE THREAD

**Issue by Jafalex** [Martvvliet/homebridge-denon-heos#48]
I believe it is expected to have to re-add the accessory via the Home app after doing some tweaks/changes in the config of the plugin. 
I scratched my head for 5 minutes looking at a "not responding" tile before thinking about adding a new accessory, and there it was. 

Suggestion is to make it a bit more obvious that that step is needed. Unless of course it is a bug, and it's possible to modify the same accessory without having to add it again.

Thanks for a great plugin!

**Comment by Martvvliet** [comment]
@Jafalex Thank you for reporting this. Currently, it generates a "unique accessory" based on name, IP, Zone and type. It has to be unique. What I can do is use just the name, so you can change the IP without having to re-add the device. What do you think of that?

**Comment by Jafalex** [comment]
Interesting as all it took to generate a new accessory was adding the ``"volumeAsFan": true`` parameter. ``Name``, ``IP`` and ``Zone`` were unchanged. Note that I  am not using ``Type``.
Only relying on ``name`` change to recreate the unique accessory sounds like a good idea to me. Cheers

**Comment by schemers** [comment]
Hum, this also happened to me when updating to latest. My IP address is reserved so I don’t think any of those values changed.

**Comment by schemers** [comment]
Ah, looks like the hash was recently updated to include zone, which probably did it.

**Comment by Martvvliet** [comment]
I made some changes in 2.9.5 Can you verify if anything has changed since this update?

**Comment by Jafalex** [comment]
Sorry for missing your question here. This issue definitely seems to be fixed. I wonder if it introduced another issue where the volume level always resets to zero, even after changing the volume, when I release my finger from the level goes straight back to zero (but the actual volume remains to where I set it). It’s like the plug-in couldn’t read the volume level and set the fan level accordingly. 
Cheers
