### ISSUE TITLE
Volume accessory keeps getting replaced

### ISSUE THREAD

**Issue by rbswift** [Martvvliet/homebridge-denon-heos#50]
Hi,

I frequently have to move my lightbulb volume control into the correct room, reset the icon, remove from favourites & status. It seems to get removed and replaced occasionally. I haven't been able to determine why. It's not every restart of homebridge but maybe when up update something? All other accessories (I have lots) are fine but this one keeps getting reset??

```
            "volumeControl": [
                {
                    "name": "Dining Amp Volume",
                    "ip": "192.168.188.11",
                    "port": "80",
                    "volumeLimit": 60,
                    "zone": 2
                }
            ]
```

**Comment by Martvvliet** [comment]
@rbswift Thank you for your input. Everything you have configured looks fine. Not sure why this is happening, so I will find this out. Do you see in your LOG something like `New volumeControl configured: ` when the reset happens?

**Comment by rbswift** [comment]
Thanks for responding. This has not happened for a while now so maybe it was fixed in a release or has somehow otherwise stabilised. I will close the issue for now and reopen if I see it happen again. Cheers
