### ISSUE TITLE
Can’t Change Input

### ISSUE THREAD

**Issue by w1llf0rd** [Martvvliet/homebridge-denon-heos#52]
Hello! I got the plug-in up and running and the on and off feature works great, however it won’t change inputs whenever I try inside the home app. Any ideas why?

**Comment by Martvvliet** [comment]
Can you post your config?

**Comment by w1llf0rd** [comment]
"name": "TV Reciever",
                    "ip": "192.168.xxxx",
                    "zone": 1,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "CBL/SAT",
                            "name": "Televison"
                        },
                        {
                            "inputID": "Blu-ray",
                            "name": "Blu-ray"
                        },
                        {
                            "inputID": "GAME",
                            "name": "Apple TV"
                        },
                        {
                            "inputID": "MPLAY",
                            "name": "Xbox"
                        },
                        {
                            "inputID": "AUX1",
                            "name": "Wii"

**Comment by Pauzi2304** [comment]
Hi!
Try to change the inpudID's like this: "CBL/SAT" -> "SAT/CBL" and "Blu-ray" -> "BD".

**Comment by Martvvliet** [comment]
@w1llf0rd Thank you for posting this and sorry for the late reply. Had some busy days last months. As @Pauzi2304 stated, the inputID is indeed different. Are only those the issue, or is the"GAME" and "AUX1" also not working?
