### ISSUE TITLE
"Volume as Fan" device loses room assignment after a restart

### ISSUE THREAD

**Issue by dustindclark** [Martvvliet/homebridge-denon-heos#54]
Maybe generating a new UUID for the volume device with each restart?

**Comment by dustindclark** [comment]
My device has a reserved IP, by the way.  The power control also retains its assignment..so this is limited to the volume appliance.

**Comment by Martvvliet** [comment]
Sadly enough this is known, but not sure why this is happening. I haven't had this problem myself so it's quite hard to debug. Will take a look and try to fix this after my holiday :) will be trying some things in two weeks time.

**Comment by Martvvliet** [comment]
I made some changes. As i don't have this issue in my own setup can you verify if anything has changed in 2.9.5?
