### ISSUE TITLE
New receiver icon in iOS 14?

### ISSUE THREAD

**Issue by Jafalex** [Martvvliet/homebridge-denon-heos#55]
Hi there,

I see some people on Reddit mentioned they are seeing the receiver icon using this very plugin ([here](https://imgur.com/a/h933qs6) and [here](https://www.reddit.com/r/HomeKit/comments/hfizgw/new_accessories_icons_in_ios_14/fvzseth/?utm_source=reddit&utm_medium=web2x&context=3)). It doesn't seem to be the case for me (on iOS 14 of course), am I missing something?

Thanks!

**Comment by muzzymate** [comment]
In Beta 1, it appeared in the Home app. Past Beta 1, the receiver icon seems to only appear on the "Add Accessories" screen. Once added to the home, it appears as a regular TV.

**Comment by Jafalex** [comment]
Cheers - way to keep our hopes high for the official release huh...
