### ISSUE TITLE
Receiver not showing as TV

### ISSUE THREAD

**Issue by Danton-** [Martvvliet/homebridge-denon-heos#58]
Good afternoon,

First of all I want to say that I really love your plugin. Sadly enough my X3400-H is not showing as a TV in Homebridge nor in Hoobs. Is this a known issue? Have the same problem with the homebridge-denon-tv plugin.

Kind regards, Danton

**Comment by Jafalex** [comment]
Same issue here, and for my Sony TV too. Although I fixed the TV icon issue following [this fix](https://github.com/normen/homebridge-bravia/issues/124).

The fix (set externalaccessory to true) may apply to this plugin as well, I'll test later on if nobody has.

**Comment by Martvvliet** [comment]
@Danton- Thank you. Do you mean that it is not visible at all, or is it shown as a tiny house? Maybe you have it configured wrong?

@Jafalex Yeah I had the same issue since IOS 14 release, but for me readding it was the solution. It is also shown now as a receiver instead of a TV.

**Comment by Jafalex** [comment]
> @Jafalex Yeah I had the same issue since IOS 14 release, but for me readding it was the solution. It is also shown now as a receiver instead of a TV.

Excellent! I have to say I haven't tried to re-add it yet, at the moment I still see the "tiny house" icon. I'll try re-adding ASAP prior to trying the externalaccessory trick, and I'll report back.

Cheers

**Comment by Martvvliet** [comment]
Great, what I also did was change the name in the config file, so It wouldn't use any cashed info in homekit.

**Comment by Jafalex** [comment]
Hello, that worked! 
1. Remove accessory from within the Home app
2. Clear single accessory cache from ```Homebridge Config UI X``` (top right 3 dots icon -> Homebridge Settings -> Remove Single Cached Accessory)
3. restart Homebridge
4. Add accessory from the Home app.

Stoked, thanks!

**Comment by siobhanellis** [comment]
Worked for me too. cool.

On Sep 23, 2020, at 1:33 PM, Alex <notifications@github.com<mailto:notifications@github.com>> wrote:



Hello, that worked!

  1.  Remove accessory from within the Home app
  2.  Clear single accessory cache from Homebridge Config UI X (top right 3 dots icon -> Homebridge Settings -> Remove Single Cached Accessory)
  3.  restart Homebridge
  4.  Add accessory from the Home app.

Stoked, thanks!

**Comment by Martvvliet** [comment]
Great thanks for letting me know. Will close the issue now.
