### ISSUE TITLE
Zone 3 status pull

### ISSUE THREAD

**Issue by alontim** [Martvvliet/homebridge-denon-heos#59]
Great add on!

On zone 3 the status (volume, source, on/off) is only push to the avr and wont pull (for example if i turn the zone 3 from denon app the switches remain off)

Tnx

**Comment by Martvvliet** [comment]
Clear thanks. I don't have a zone 3, so haven't tested it yet. will take a look at it.

**Comment by alontim** [comment]
Tanks for the fast answer

Do you need a video of the problem?

Alon Timianker

**Comment by Martvvliet** [comment]
Hi, Can you post me the config file of the plugin and can you test with the http://192.168.1.45:8080/goform/formZone3_Zone3XmlStatusLite.xml link if you receive on the current state. You must change the IP to your receivers IP.

**Comment by alontim** [comment]
Hey Config file:        {            "platform": "DenonAVR",            "pollInterval": 3,            "devices": [                {                    "name": "Living Room",                    "ip": "192.168.68.104",                    "switchInfoMenu": true,                    "defaultInputID": "SAT/CBL",                    "zone": 1,                    "inputs": [                        {                            "inputID": "SAT/CBL",                            "name": "HOT",                            "defaultVolume": 40                        },                        {                            "inputID": "NET",                            "name": "HEOS"                        },                        {                            "inputID": "TV",                            "name": "TV AUDIO"                        },                        {                            "inputID": "MPLAY",                            "name": "MI BOX S"                        }                    ]                },                {                    "name": "Pool",                    "ip": "192.168.68.104",                    "switchInfoMenu": true,                    "zone": 3,                    "inputs": [                        {                            "inputID": "SAT/CBL",                            "name": "HOT",                            "defaultVolume": 45                        },                        {                            "inputID": "NET",                            "name": "HEOS"                        },                        {                            "inputID": "TV",                            "name": "TV AUDIO"                        },                        {                            "inputID": "MPLAY",                            "name": "MI BOX S"                        }                    ]                }            ],            "switches": [                {                    "name": "HOT on Living",                    "ip": "192.168.68.104",                    "inputID": "SAT/CBL",                    "pollAllInput": false                },                {                    "name": "MI BOX on Living",                    "ip": "192.168.68.104",                    "inputID": "MPLAY"                },                {                    "name": "HOT on Pool",                    "ip": "192.168.68.104",                    "zone": 3,                    "inputID": "SAT/CBL"                },                {                    "name": "HEOS on pool",                    "ip": "192.168.68.104",                    "zone": 3,                    "inputID": "NET"                }            ],            "volumeControl": [                {                    "name": "Living Volume",                    "ip": "192.168.68.104",                    "volumeLimit": 100,                    "zone": 1,                    "volumeAsFan": false                },                {                    "name": "Pool Volume",                    "ip": "192.168.68.104",                    "volumeLimit": 100,                    "zone": 3,                    "volumeAsFan": false                }            ]        },  current state – every thing off<item><Power><value>OFF</value></Power><InputFuncSelect><value>NET</value></InputFuncSelect><VolumeDisplay><value>Absolute</value></VolumeDisplay><MasterVolume><value>-35</value></MasterVolume><Mute><value>off</value></Mute></i current state-on via denon app (on the homebridge plugin zone 3 is off)<item><Power><value>ON</value></Power><InputFuncSelect><value>NET</value></InputFuncSelect><VolumeDisplay><value>Absolute</value></VolumeDisplay><MasterVolume><value>-35</value></MasterVolume><Mute><value>off</value></Mute></item> current state-on via homebridge (zone 3 now “on” on homebridge switches)item><Power><value>ON</value></Power><InputFuncSelect><value>NET</value></InputFuncSelect><VolumeDisplay><value>Absolute</value></VolumeDisplay><MasterVolume><value>-35</value></MasterVolume><Mute><value>off</value></Mute></item> Thanks     From: MartvvlietSent: שבת 03 אוקטובר 2020 13:32To: Martvvliet/homebridge-denon-heosCc: alontim; AuthorSubject: Re: [Martvvliet/homebridge-denon-heos] Zone 3 status pull (#59) Hi, Can you post me the config file of the plugin and can you test with the http://192.168.1.45:8080/goform/formZone3_Zone3XmlStatusLite.xml link if you receive on the current state. You must change the IP to your receivers IP.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by alontim** [comment]
Hey

Config file:
        {
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "Living Room",
                    "ip": "192.168.68.104",
                    "switchInfoMenu": true,
                    "defaultInputID": "SAT/CBL",
                    "zone": 1,
                    "inputs": [
                        {
                            "inputID": "SAT/CBL",
                            "name": "HOT",
                            "defaultVolume": 40
                        },
                        {
                            "inputID": "NET",
                            "name": "HEOS"
                        },
                        {
                            "inputID": "TV",
                            "name": "TV AUDIO"
                        },
                        {
                            "inputID": "MPLAY",
                            "name": "MI BOX S"
                        }
                    ]
                },
                {
                    "name": "Pool",
                    "ip": "192.168.68.104",
                    "switchInfoMenu": true,
                    "zone": 3,
                    "inputs": [
                        {
                            "inputID": "SAT/CBL",
                            "name": "HOT",
                            "defaultVolume": 45
                        },
                        {
                            "inputID": "NET",
                            "name": "HEOS"
                        },
                        {
                            "inputID": "TV",
                            "name": "TV AUDIO"
                        },
                        {
                            "inputID": "MPLAY",
                            "name": "MI BOX S"
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "HOT on Living",
                    "ip": "192.168.68.104",
                    "inputID": "SAT/CBL",
                    "pollAllInput": false
                },
                {
                    "name": "MI BOX on Living",
                    "ip": "192.168.68.104",
                    "inputID": "MPLAY"
                },
                {
                    "name": "HOT on Pool",
                    "ip": "192.168.68.104",
                    "zone": 3,
                    "inputID": "SAT/CBL"
                },
                {
                    "name": "HEOS on pool",
                    "ip": "192.168.68.104",
                    "zone": 3,
                    "inputID": "NET"
                }
            ],
            "volumeControl": [
                {
                    "name": "Living Volume",
                    "ip": "192.168.68.104",
                    "volumeLimit": 100,
                    "zone": 1,
                    "volumeAsFan": false
                },
                {
                    "name": "Pool Volume",
                    "ip": "192.168.68.104",
                    "volumeLimit": 100,
                    "zone": 3,
                    "volumeAsFan": false
                }
            ]
        },


**current state – every thing off**
<item>
<Power>
<value>OFF</value>
</Power>
<InputFuncSelect>
<value>NET</value>
</InputFuncSelect>
<VolumeDisplay>
<value>Absolute</value>
</VolumeDisplay>
<MasterVolume>
<value>-35</value>
</MasterVolume>
<Mute>
<value>off</value>
</Mute>
</i

**current state-on via denon app (on the homebridge plugin zone 3 is off)**
<item>
<Power>
<value>ON</value>
</Power>
<InputFuncSelect>
<value>NET</value>
</InputFuncSelect>
<VolumeDisplay>
<value>Absolute</value>
</VolumeDisplay>
<MasterVolume>
<value>-35</value>
</MasterVolume>
<Mute>
<value>off</value>
</Mute>
</item>

**current state-on via homebridge (zone 3 now “on” on homebridge switches)**
item>
<Power>
<value>ON</value>
</Power>
<InputFuncSelect>
<value>NET</value>
</InputFuncSelect>
<VolumeDisplay>
<value>Absolute</value>
</VolumeDisplay>
<MasterVolume>
<value>-35</value>
</MasterVolume>
<Mute>
<value>off</value>
</Mute>
</item>

Thanks

**Comment by alontim** [comment]
hey

text file attached

tnx

**Comment by alontim** [comment]
hey

text file attached

tnx
[New Text Document.txt](https://github.com/Martvvliet/homebridge-denon-heos/files/5321607/New.Text.Document.txt)

**Comment by Martvvliet** [comment]
Thanks. Should be fixed in latest update :)

**Comment by alontim** [comment]
Fixed! Amazing. Tnx
