### ISSUE TITLE
Error adding TV Accesssory

### ISSUE THREAD

**Issue by MarketSqHero** [Martvvliet/homebridge-denon-heos#61]
Hi;

Getting the following error when trying to add a TV accessory on a x2400H model

ERROR: Could not add TV accessory.

Also adding more than one switch shows only the last one added

**Comment by Martvvliet** [comment]
Hi, Can you add you config?

**Comment by MarketSqHero** [comment]
Added the reelvant section below. So in the Homebridge accessory screen, the Xbox switch shows, but that's all, no Apple TV switch or TV device.

**Comment by MarketSqHero** [comment]
{
            "debugToInfo": false,
            "devices": [
                {
                    "name": "Denon Receiver HEOS",
                    "ip": "192.168.0.110",
                    "zone": 1,
                    "switchInfoMenu": false,
                    "defaultInputID": "MPLAY",
                    "inputs": [
                        null,
                        {
                            "inputID": "GAME",
                            "name": "Xbox"
                        },
                        {
                            "inputID": "TV",
                            "name": "TV Channel"
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "Apple TV",
                    "ip": "192.168.0.110",
                    "zone": 1,
                    "pollAllInput": false
                },
                {
                    "name": "Xbox",
                    "ip": "192.168.0.110",
                    "zone": 1,
                    "inputID": "GAME",
                    "pollAllInput": false
                }
            ],
            "volumeControl": [
                {
                    "name": "Denon Volume",
                    "ip": "192.168.0.110",
                    "zone": 1,
                    "controlType": "bulb",
                    "volumeLimit": 60
                }
            ],
            "platform": "DenonAVR"
        }

**Comment by MarketSqHero** [comment]
Hi;

I noticed lot's of formatting issues in the config after I posted it. I modified it manually and all is working as expected now. I think the Homebridge Config UI part isn't working properly

**Comment by Martvvliet** [comment]
Hmm, interesting but good to hear its working now. I will take a look at it. I can close the issue now?

**Comment by MarketSqHero** [comment]
Yes, will test properly later. I have a newer model so have to use Telnet unfortunately but it's better than nothing. Thanks for your work :)

**Comment by Martvvliet** [comment]
Great, let me know if there are issues. Haven't tested the telnet that throughly so feedback is welcome:)
