### ISSUE TITLE
[2020-10-22 12:34:07] [DenonAVR] ERROR: Can't connect to receiver with ip: 192.168.XXX.YYY and port: 8080

### ISSUE THREAD

**Issue by drheck** [Martvvliet/homebridge-denon-heos#63]
Hi,
i have a new Denon Receiver X2700H since yesterday.
I have configured your plugin (see below), but i get the error in the subject.
If i try this: http://192.168.XXX.YYY:8080/goform/formMainZone_MainZoneXmlStatusLite.xml
i get the correct answer.
So what is wrong?
Thank you for your answer.
Peter
        {
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "Denon Receiver",
                    "ip": "192.168.XXX.YYY",
                    "switchInfoMenu": true,
                    "defaultInputID": "SAT/CBL",
                    "zone": 1,
                    "port": 8080,
                    "inputs": [
                        {
                            "inputID": "MPLAY",
                            "name": "Apple TV",
                            "defaultVolume": 32
                        },
                        {
                            "inputID": "IRADIO",
                            "name": "Radio"
                        },
                        {
                            "inputID": "SAT/CBL",
                            "name": "VU+"
                        }
                    ]
                }
            ]
        },

**Comment by Martvvliet** [comment]
Hi, can you try with port 80 and with telnet. You can also just leave it auto so it will automatically detect the correct settings. Please let me know if anything changes

**Comment by drheck** [comment]
Hi, 
i tried:
1) telnet 192.168.XXX.YYY -> nothing happens cursor is blinking. After pressing CTRL-+
i see a Willkommen and i am in a telnet session.
I can write st an i am connected with the ip.
2) telnet 192.168.XXX.YYY 80 -> after a few seconds telnet come back to the dos prompt
3) same with 8080

**Comment by drheck** [comment]
I have also configured a plugin             "accessory": "HTTP-SWITCH"
and this could also not connect to the new receiver. With my old receiver (X1100W, other ip and no HEOS) there was no problem, but your plugin had the same problem.
[2020-10-22 13:27:15] [Denon] getStatus() doing http request...
[2020-10-22 13:27:18] [Zone2] getStatus() failed: connect EHOSTUNREACH 192.168.XXX.YYY:80
[2020-10-22 13:27:18] [Denon] getStatus() failed: connect EHOSTUNREACH 192.168.XXX.YYY:80

**Comment by drheck** [comment]
Sorry. After a Reboot of my roouter and the receiver... it works.
