### ISSUE TITLE
Logs spamming with getMuteState & getVolume

### ISSUE THREAD

**Issue by koles0ff** [Martvvliet/homebridge-denon-heos#66]
Hello,

please advise me on my issue. I would like to disable mentioned log events. It is quite annoying:

> [11/5/2020, 8:23:09 PM] [DenonAVR] getMuteState
> [11/5/2020, 8:23:09 PM] [DenonAVR] getVolume
> [11/5/2020, 8:23:10 PM] [DenonAVR] getMuteState
> [11/5/2020, 8:23:10 PM] [DenonAVR] getVolume
> [11/5/2020, 8:23:10 PM] [DenonAVR] getMuteState
> [11/5/2020, 8:23:10 PM] [DenonAVR] getVolume
> [11/5/2020, 8:23:12 PM] [DenonAVR] getMuteState
> [11/5/2020, 8:23:12 PM] [DenonAVR] getVolume
> [11/5/2020, 8:23:17 PM] [DenonAVR] getMuteState
> [11/5/2020, 8:23:17 PM] [DenonAVR] getVolume
> [11/5/2020, 8:27:19 PM] [DenonAVR] getMuteState
> [11/5/2020, 8:27:19 PM] [DenonAVR] getVolume
> [11/5/2020, 8:27:22 PM] [DenonAVR] getMuteState
> [11/5/2020, 8:27:22 PM] [DenonAVR] getVolume

here is my confing:
_{
            "debugToInfo": false,
            "devices": [
                {
                    "name": "Marantz Receiver",
                    "ip": "192.168.1.65",
                    "zone": 1,
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "MPLAY",
                            "name": "Apple TV",
                            "defaultVolume": 50
                        },
                        {
                            "inputID": "GAME",
                            "name": "Playstation",
                            "defaultVolume": 35
                        }
                    ]
                }
            ],
            "switches": [
                {
                    "name": "Denon Receiver Input",
                    "zone": 1,
                    "pollAllInput": false
                }
            ],
            "volumeControl": [
                {
                    "name": "Marantz volume",
                    "ip": "192.168.1.65",
                    "zone": 1,
                    "volumeAsFan": false,
                    "volumeLimit": 70
                }
            ],
            "platform": "DenonAVR"
        },_

Thanks in advance.

**Comment by Martvvliet** [comment]
fixed in 2.9.7 sorry didn't remove it properly. Thanks for posting issue
