### ISSUE TITLE
"auto" port not working - neither is hardcoding 80

### ISSUE THREAD

**Issue by Gibbon99** [Martvvliet/homebridge-denon-heos#8]
Hi

I have upgraded to 2.0.6 - and am now getting the following error on startup

`Jan 20 11:23:17 monitor homebridge[26556]: [20/01/2020, 11:23:17 am] [DenonAVR] Error while getting information of receiver with IP: 10.1.1.12. Error: connect ECONNREFUSED 10.1.1.12:60006
Jan 20 11:23:17 monitor homebridge[26556]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:16) {
Jan 20 11:23:17 monitor homebridge[26556]:   errno: -111,
Jan 20 11:23:17 monitor homebridge[26556]:   code: 'ECONNREFUSED',
Jan 20 11:23:17 monitor homebridge[26556]:   syscall: 'connect',
Jan 20 11:23:17 monitor homebridge[26556]:   address: '10.1.1.12',
Jan 20 11:23:17 monitor homebridge[26556]:   port: 60006
Jan 20 11:23:17 monitor homebridge[26556]: }
Jan 20 11:23:17 monitor homebridge[26556]: [20/01/2020, 11:23:17 am] [DenonAVR] Error while getting information of receiver with IP: 10.1.1.12. Error: connect ECONNREFUSED 10.1.1.12:60006
Jan 20 11:23:17 monitor homebridge[26556]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1136:16) {
Jan 20 11:23:17 monitor homebridge[26556]:   errno: -111,
Jan 20 11:23:17 monitor homebridge[26556]:   code: 'ECONNREFUSED',
Jan 20 11:23:17 monitor homebridge[26556]:   syscall: 'connect',
Jan 20 11:23:17 monitor homebridge[26556]:   address: '10.1.1.12',
Jan 20 11:23:17 monitor homebridge[26556]:   port: 60006
Jan 20 11:23:17 monitor homebridge[26556]: }
`

I have tired both 'auto' and '80' as the port - but it keeps defauling to port 60006.

`     {
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "Denon Receiver",
                    "ip": "10.1.1.12",
		    "port": "auto",
                    "switchInfoMenu": true,
                    "inputs": [
                        {
                            "inputID": "MPLAY",
                            "name": "MythTV"
                        },
`

Thanks.

**Comment by Gibbon99** [comment]
I can fix it by changing 8080 to 80 here:

        retrieveDenonInformation() {
                if (traceOn)
                        this.log.debug('retrieveDenonInformation');

                var that = this;
                request('http://' + this.ip + ':60006/upnp/desc/aios_device/aios_device.xml', function(error, response, body) {
                        if(error) {
                                that.devInfoSet = true;
                                that.log.error("Error while getting information of receiver with IP: %s. %s", that.ip, error);
                                if (that.webAPIPort === 'auto')
                                        that.webAPIPort = 80;    // change from 8080

Also in the config.json file - if I have "port": 80 ( without quotes) I get the following errors:

Jan 20 11:44:34 monitor homebridge[29123]: #033[0;37m[20/01/2020, 11:44:34 am] #033[0m#033[0;36m[Config]#033[0m #033[0;33mHomebridge Config UI X v4.7.0 is listening on 0.0.0.0 port 8080#033[0m
Jan 20 11:44:38 monitor homebridge[29123]: #033[0;37m[20/01/2020, 11:44:38 am] #033[0m#033[0;36m[Config]#033[0m #033[0;33m[HapClient] Cannot load accessories. No Homebridge instances have been discovered.#033[0m
Jan 20 11:44:38 monitor homebridge[29123]: #033[0;37m[20/01/2020, 11:44:38 am] #033[0m#033[0;36m[Config]#033[0m #033[0;33m[HapClient] Cannot load accessories. No Homebridge instances have been discovered.#033[0m

If I put quotes around the port - "port": "80" - everything works ok. I still get the initial messages about attempting to access the device on port 60006.

These are the only ports open on my device: ( AVR-X1200W )

PORT     STATE SERVICE       REASON
23/tcp   open  telnet        syn-ack ttl 128
80/tcp   open  http          syn-ack ttl 128
443/tcp  open  https         syn-ack ttl 128
1027/tcp open  IIS           syn-ack ttl 128
5000/tcp open  upnp          syn-ack ttl 128
5001/tcp open  commplex-link syn-ack ttl 128
6666/tcp open  irc           syn-ack ttl 128
8080/tcp open  http-proxy    syn-ack ttl 128

**Comment by Martvvliet** [comment]
@Gibbon99 Thank you for leaving feedback. I made some changes so it should work now. I pushed the update for the autodiscovery bug to the bugfix branch. Can you test if this does work on your receivers? If you turn on debug information in the log you should also see the correct port for the device information for your devices. Can you send me that too? If it is working now, I can push it to NPM

**Comment by Martvvliet** [comment]
A similar problem is handled in #10 so I will close this issue now.
