### ISSUE TITLE
Device does not appear in Home App

### ISSUE THREAD

**Issue by dppeak** [Martvvliet/homebridge-denon-heos#9]
I have installed the latest version 2.0.6 and configured is with the following.

`        {
            "platform": "DenonAVR",
            "pollInterval": 3,
            "devices": [
                {
                    "name": "Denon AVR",
                    "ip": "192.168.7.210",
                    "port": 80,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "inputID": "BD",
                            "name": "Apple TV"
                        },
                        {
                            "inputID": "GAME",
                            "name": "Control4"
                        },
                        {
                            "inputID": "SAT/CBL",
                            "name": "Cable"
                        },
                        {
                            "inputID": "DVD",
                            "name": "Blu-ray"
                        }
                    ]
                }
            ]
        }
`

I get the error that others are getting:

`Error while getting information of receiver with IP: 192.168.7.210. Error: connect ECONNREFUSED 192.168.7.210:60006
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.7.210',
  port: 60006
}`

However, I am never seeing the device in the Home app.  I have several other plugins on this Homebridge instance, and those accessories are showing, but no matter the configuration change I make, I never see the Denon AVR.  (X1300H)

I have also removed cached accessories file and restarted the app, but no changes.

**Comment by Martvvliet** [comment]
@dppeak. Remember that you have to add the receiver manually as an accessory after adding the homebridge accessory. This is necessary to enable the possibility of multiple devices that have support for the remote service. If you tried this already what might help is changing the 80 to "80" for now. If this is the solution, it will be fixed in following release. Also the auto port config should work in this release. 
The second error you can ignore for now. This will also be fixed in the following release.

**Comment by dppeak** [comment]
Okay, I had thought that I had tried to add it manually before in the home app.  This time I tried through the Eve app and clicked on the "I Don't have a code..." button and then the Denon showed up on that screen and used the code from the log (echoed from the plugin).  Success!

Thanks!

**Comment by Martvvliet** [comment]
Great :) enjoy and if you have feedback please let me know. 
Thanks.
